version: 4.2
os: linux
files:
  - source: /
    destination: /data/apps/stage_platform_appspec/l-ui
hooks:
  ApplicationStop:
    - location: scripts/stage/stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/stage/beforeInstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/stage/afterInstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/stage/start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/stage/validate_service.sh
      timeout: 300
      runas: root