version: 4.2
os: linux
files:
  - source: /
    destination: /data/apps/development_platform_appspec/l-ui
hooks:
  ApplicationStop:
    - location: scripts/development/stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/development/beforeInstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/development/afterInstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/development/start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/development/validate_service.sh
      timeout: 300
      runas: root