version: 4.2
os: linux
files:
  - source: /
    destination: /data/apps/production_platform_appspec/l-ui
hooks:
  ApplicationStop:
    - location: scripts/production/stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/production/beforeInstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/production/afterInstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/production/start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/production/validate_service.sh
      timeout: 300
      runas: root